//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.25 at 04:58:00 PM CEST 
//


package org.wybecom.talk.jtapi.stateserver.client.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stateserverclientconfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stateserverclientconfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stateserverclient" type="{http://xml.netbeans.org/schema/stateserverclientconfig}xmlstateserverclient" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stateserverclientconfig", propOrder = {
    "stateserverclient"
})
public class Stateserverclientconfig {

    protected List<Xmlstateserverclient> stateserverclient;

    /**
     * Gets the value of the stateserverclient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateserverclient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateserverclient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Xmlstateserverclient }
     * 
     * 
     */
    public List<Xmlstateserverclient> getStateserverclient() {
        if (stateserverclient == null) {
            stateserverclient = new ArrayList<Xmlstateserverclient>();
        }
        return this.stateserverclient;
    }

}
