//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3603
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par xsd, Version=2.0.50727.42.
// 
namespace Wybecom.TalkPortal.Cisco.ExtensionMobility.Query {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("query", Namespace="", IsNullable=false)]
    public partial class queryType {
        
        private appInfoType appInfoField;
        
        private object itemField;
        
        /// <remarks/>
        public appInfoType appInfo {
            get {
                return this.appInfoField;
            }
            set {
                this.appInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deviceUserQuery", typeof(deviceUserQueryType))]
        [System.Xml.Serialization.XmlElementAttribute("userDevicesQuery", typeof(userDevicesQueryType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        public override string ToString()
        {
            string result = "xml=<query><appInfo><appID>";
            result += appInfo.appID.Value + "</appID><appCertificate>";
            result += appInfo.appCertificate.Value + "</appCertificate></appInfo>";
            if (Item is deviceUserQueryType)
            {
                result += "<deviceUserQuery>";
                foreach (deviceNameType s in ((deviceUserQueryType)Item).deviceName)
                {
                    result += "<deviceName>" + s.Value + "</deviceName>";
                }
                result += "</deviceUserQuery>";
            }
            else if (Item is userDevicesQueryType)
            {
                result += "<userDevicesQuery>";
                foreach (userIDType s in ((userDevicesQueryType)Item).userID)
                {
                    result += "<userID>" + s.Value + "</userID>";
                }
                result += "</userDevicesQuery>";
            }
            
            result += "</query>";
            return result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("appInfo", Namespace="", IsNullable=false)]
    public partial class appInfoType {
        
        private appIDType appIDField;
        
        private appCertificateType appCertificateField;
        
        /// <remarks/>
        public appIDType appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public appCertificateType appCertificate {
            get {
                return this.appCertificateField;
            }
            set {
                this.appCertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("appID", Namespace="", IsNullable=false)]
    public partial class appIDType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("userDevicesQuery", Namespace="", IsNullable=false)]
    public partial class userDevicesQueryType {
        
        private userIDType[] userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userID")]
        public userIDType[] userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("userID", Namespace="", IsNullable=false)]
    public partial class userIDType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("deviceUserQuery", Namespace="", IsNullable=false)]
    public partial class deviceUserQueryType {
        
        private deviceNameType[] deviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deviceName")]
        public deviceNameType[] deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("deviceName", Namespace="", IsNullable=false)]
    public partial class deviceNameType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("appCertificate", Namespace="", IsNullable=false)]
    public partial class appCertificateType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
