//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.25 at 04:58:00 PM CEST 
//

/**
 * \package
 * All state server settings related classes
 */
package org.wybecom.talk.jtapi.stateserver.client.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Configuration_QNAME = new QName("http://xml.netbeans.org/schema/stateserverclientconfig", "configuration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xmlstateserverclient }
     * 
     */
    public Xmlstateserverclient createXmlstateserverclient() {
        return new Xmlstateserverclient();
    }

    /**
     * Create an instance of {@link Stateserverclientconfig }
     * 
     */
    public Stateserverclientconfig createStateserverclientconfig() {
        return new Stateserverclientconfig();
    }
    
    /**
     * Create an instance of {@link Xmlevent }
     * 
     */
    public Xmlevent createXmlevent() {
        return new Xmlevent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stateserverclientconfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.netbeans.org/schema/stateserverclientconfig", name = "configuration")
    public JAXBElement<Stateserverclientconfig> createConfiguration(Stateserverclientconfig value) {
        return new JAXBElement<Stateserverclientconfig>(_Configuration_QNAME, Stateserverclientconfig.class, null, value);
    }

}
