//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.25 at 04:06:34 PM CEST 
//
/*
    This file is part of TALK (Wybecom).

    TALK is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2 as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TALK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with TALK.  If not, see <http://www.gnu.org/licenses/gpl-2.0.html>.
 
    TALK is based upon:
    - Sun JTAPI http://java.sun.com/products/jtapi/
    - JulMar TAPI http://julmar.com/
    - Asterisk.Net http://sourceforge.net/projects/asterisk-dotnet/
 
*/

package org.wybecom.talk.jtapi.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \brief Java class for xmlprovider complex type.
 * <p>Java class for xmlprovider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlprovider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ctiprovider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctiuser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctiuserpassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backupctiprovider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmlprovider", propOrder = {
    "ctiprovider",
    "ctiuser",
    "ctiuserpassword",
    "backupctiprovider"
})
public class Xmlprovider {

    @XmlElement(required = true)
    protected String ctiprovider;
    @XmlElement(required = true)
    protected String ctiuser;
    @XmlElement(required = true)
    protected String ctiuserpassword;
    @XmlElement(required = true)
    protected String backupctiprovider;

    /**
     * Gets the value of the ctiprovider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtiprovider() {
        return ctiprovider;
    }

    /**
     * Sets the value of the ctiprovider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtiprovider(String value) {
        this.ctiprovider = value;
    }

    /**
     * Gets the value of the ctiuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtiuser() {
        return ctiuser;
    }

    /**
     * Sets the value of the ctiuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtiuser(String value) {
        this.ctiuser = value;
    }

    /**
     * Gets the value of the ctiuserpassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtiuserpassword() {
        return ctiuserpassword;
    }

    /**
     * Sets the value of the ctiuserpassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtiuserpassword(String value) {
        this.ctiuserpassword = value;
    }

    /**
     * Gets the value of the backupctiprovider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupctiprovider() {
        return backupctiprovider;
    }

    /**
     * Sets the value of the backupctiprovider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupctiprovider(String value) {
        this.backupctiprovider = value;
    }

}
