//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 03:03:49 PM CET 
//


package org.wybecom.talk.team.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wybecom.talk.team.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Configuration_QNAME = new QName("http://xml.netbeans.org/schema/teamconfig", "configuration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wybecom.talk.team.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Teamconfig }
     * 
     */
    public Teamconfig createTeamconfig() {
        return new Teamconfig();
    }

    /**
     * Create an instance of {@link Xmlteam }
     * 
     */
    public Xmlteam createXmlteam() {
        return new Xmlteam();
    }

    /**
     * Create an instance of {@link Xmlacdmanageraddressgroup }
     * 
     */
    public Xmlacdmanageraddressgroup createXmlacdmanageraddressgroup() {
        return new Xmlacdmanageraddressgroup();
    }

    /**
     * Create an instance of {@link Xmlteamprovider }
     * 
     */
    public Xmlteamprovider createXmlteamprovider() {
        return new Xmlteamprovider();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Teamconfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.netbeans.org/schema/teamconfig", name = "configuration")
    public JAXBElement<Teamconfig> createConfiguration(Teamconfig value) {
        return new JAXBElement<Teamconfig>(_Configuration_QNAME, Teamconfig.class, null, value);
    }

}
