//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.01 at 03:03:49 PM CET 
//


package org.wybecom.talk.team.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmlteamprovider complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlteamprovider">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="teamctiprovider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="teamctiuser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="teamctiuserpassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="teambackupctiprovider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmlteamprovider", propOrder = {
    "teamctiprovider",
    "teamctiuser",
    "teamctiuserpassword",
    "teambackupctiprovider"
})
public class Xmlteamprovider {

    @XmlElement(required = true)
    protected String teamctiprovider;
    @XmlElement(required = true)
    protected String teamctiuser;
    @XmlElement(required = true)
    protected String teamctiuserpassword;
    @XmlElement(required = true)
    protected String teambackupctiprovider;

    /**
     * Gets the value of the teamctiprovider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamctiprovider() {
        return teamctiprovider;
    }

    /**
     * Sets the value of the teamctiprovider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamctiprovider(String value) {
        this.teamctiprovider = value;
    }

    /**
     * Gets the value of the teamctiuser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamctiuser() {
        return teamctiuser;
    }

    /**
     * Sets the value of the teamctiuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamctiuser(String value) {
        this.teamctiuser = value;
    }

    /**
     * Gets the value of the teamctiuserpassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamctiuserpassword() {
        return teamctiuserpassword;
    }

    /**
     * Sets the value of the teamctiuserpassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamctiuserpassword(String value) {
        this.teamctiuserpassword = value;
    }

    /**
     * Gets the value of the teambackupctiprovider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeambackupctiprovider() {
        return teambackupctiprovider;
    }

    /**
     * Sets the value of the teambackupctiprovider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeambackupctiprovider(String value) {
        this.teambackupctiprovider = value;
    }

}
