//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3603
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
[System.Xml.Serialization.XmlRootAttribute("directory", Namespace="http://wybecom.org/DatasourceConfiguration.xsd", IsNullable=false)]
public partial class DirectoryType {
    
    private object itemField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cisco", typeof(CiscoDatasourceType))]
    [System.Xml.Serialization.XmlElementAttribute("ldap", typeof(LdapDatasourceType))]
    [System.Xml.Serialization.XmlElementAttribute("sql", typeof(SqlDatasourceType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
public partial class CiscoDatasourceType {
    
    private string serverField;
    
    private string axluserField;
    
    private string axluserpwdField;
    
    private FieldFormatter[] fieldFormattersField;
    
    private CiscoIPPhoneFilterType ipphonefilterField;
    
    /// <remarks/>
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    public string axluser {
        get {
            return this.axluserField;
        }
        set {
            this.axluserField = value;
        }
    }
    
    /// <remarks/>
    public string axluserpwd {
        get {
            return this.axluserpwdField;
        }
        set {
            this.axluserpwdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("fieldFormatter")]
    public FieldFormatter[] fieldFormatters {
        get {
            return this.fieldFormattersField;
        }
        set {
            this.fieldFormattersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CiscoIPPhoneFilterType ipphonefilter {
        get {
            return this.ipphonefilterField;
        }
        set {
            this.ipphonefilterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
public partial class FieldFormatter {
    
    private string fieldNameField;
    
    private string valueField;
    
    private FieldType fieldTypeField;
    
    public FieldFormatter() {
        this.fieldTypeField = FieldType.Other;
    }
    
    /// <remarks/>
    public string fieldName {
        get {
            return this.fieldNameField;
        }
        set {
            this.fieldNameField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(FieldType.Other)]
    public FieldType fieldType {
        get {
            return this.fieldTypeField;
        }
        set {
            this.fieldTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
public enum FieldType {
    
    /// <remarks/>
    Identity,
    
    /// <remarks/>
    Mail,
    
    /// <remarks/>
    Telephone,
    
    /// <remarks/>
    GSM,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
public partial class LdapDatasourceType {
    
    private string serverField;
    
    private string authenticationTypeField;
    
    private string userField;
    
    private string userPasswordField;
    
    private string targetOUField;
    
    private string[] ldapAttributesField;
    
    private string ldapFilterField;
    
    private int pageSizeField;
    
    private int nbPagesField;
    
    private FieldFormatter[] fieldFormattersField;
    
    private CiscoIPPhoneFilterType ipphonefilterField;
    
    public LdapDatasourceType() {
        this.authenticationTypeField = "Anonymous";
        this.ldapFilterField = "(objectClass=*)";
    }
    
    /// <remarks/>
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    public string authenticationType {
        get {
            return this.authenticationTypeField;
        }
        set {
            this.authenticationTypeField = value;
        }
    }
    
    /// <remarks/>
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    public string userPassword {
        get {
            return this.userPasswordField;
        }
        set {
            this.userPasswordField = value;
        }
    }
    
    /// <remarks/>
    public string targetOU {
        get {
            return this.targetOUField;
        }
        set {
            this.targetOUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ldapAttribute", IsNullable=false)]
    public string[] ldapAttributes {
        get {
            return this.ldapAttributesField;
        }
        set {
            this.ldapAttributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ldapFilter {
        get {
            return this.ldapFilterField;
        }
        set {
            this.ldapFilterField = value;
        }
    }
    
    /// <remarks/>
    public int pageSize {
        get {
            return this.pageSizeField;
        }
        set {
            this.pageSizeField = value;
        }
    }
    
    /// <remarks/>
    public int nbPages {
        get {
            return this.nbPagesField;
        }
        set {
            this.nbPagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("fieldFormatter")]
    public FieldFormatter[] fieldFormatters {
        get {
            return this.fieldFormattersField;
        }
        set {
            this.fieldFormattersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CiscoIPPhoneFilterType ipphonefilter {
        get {
            return this.ipphonefilterField;
        }
        set {
            this.ipphonefilterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
public partial class CiscoIPPhoneFilterType {
    
    private string firstnamemapField;
    
    private string lastnamemapField;
    
    private string telephonenumbermapField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string firstnamemap {
        get {
            return this.firstnamemapField;
        }
        set {
            this.firstnamemapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastnamemap {
        get {
            return this.lastnamemapField;
        }
        set {
            this.lastnamemapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telephonenumbermap {
        get {
            return this.telephonenumbermapField;
        }
        set {
            this.telephonenumbermapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/DatasourceConfiguration.xsd")]
public partial class SqlDatasourceType {
    
    private string dsnField;
    
    private string uidField;
    
    private string pwdField;
    
    private string commandField;
    
    private string sqlFilterField;
    
    private FieldFormatter[] fieldFormattersField;
    
    private CiscoIPPhoneFilterType ipphonefilterField;
    
    /// <remarks/>
    public string dsn {
        get {
            return this.dsnField;
        }
        set {
            this.dsnField = value;
        }
    }
    
    /// <remarks/>
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    public string pwd {
        get {
            return this.pwdField;
        }
        set {
            this.pwdField = value;
        }
    }
    
    /// <remarks/>
    public string command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string sqlFilter {
        get {
            return this.sqlFilterField;
        }
        set {
            this.sqlFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("fieldFormatter")]
    public FieldFormatter[] fieldFormatters {
        get {
            return this.fieldFormattersField;
        }
        set {
            this.fieldFormattersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CiscoIPPhoneFilterType ipphonefilter {
        get {
            return this.ipphonefilterField;
        }
        set {
            this.ipphonefilterField = value;
        }
    }
}
