//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4952
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CodifModel", "FK_Calls_Calls", "Codif", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Wybecom.TalkPortal.Providers.Codif), "Calls", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wybecom.TalkPortal.Providers.Calls))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CodifModel", "FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddressGroup", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wybecom.TalkPortal.Providers.ACDManagerAddressGroup), "ACDManagerAddress", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wybecom.TalkPortal.Providers.ACDManagerAddress))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CodifModel", "FK_Team_ACDManagerAddressGroup", "ACDManagerAddressGroup", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wybecom.TalkPortal.Providers.ACDManagerAddressGroup), "Team", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wybecom.TalkPortal.Providers.Team))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CodifModel", "TeamMemberTeam", "Team", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wybecom.TalkPortal.Providers.Team), "TeamMember", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wybecom.TalkPortal.Providers.TeamMember))]

// Nom du fichier d'origine :
// Date de génération : 05/04/2011 15:29:58
namespace Wybecom.TalkPortal.Providers
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifEntities dans le schéma.
    /// </summary>
    public partial class CodifEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initialise un nouvel objet CodifEntities à l'aide de la chaîne de connexion trouvée dans la section « CodifEntities » du fichier de configuration d'application.
        /// </summary>
        public CodifEntities() : 
                base("name=CodifEntities", "CodifEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet CodifEntities.
        /// </summary>
        public CodifEntities(string connectionString) : 
                base(connectionString, "CodifEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialise un nouvel objet CodifEntities.
        /// </summary>
        public CodifEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CodifEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Il n'existe aucun commentaire pour Calls dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Calls> Calls
        {
            get
            {
                if ((this._Calls == null))
                {
                    this._Calls = base.CreateQuery<Calls>("[Calls]");
                }
                return this._Calls;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Calls> _Calls;
        /// <summary>
        /// Il n'existe aucun commentaire pour Codif dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Codif> Codif
        {
            get
            {
                if ((this._Codif == null))
                {
                    this._Codif = base.CreateQuery<Codif>("[Codif]");
                }
                return this._Codif;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Codif> _Codif;
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddress dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ACDManagerAddress> ACDManagerAddress
        {
            get
            {
                if ((this._ACDManagerAddress == null))
                {
                    this._ACDManagerAddress = base.CreateQuery<ACDManagerAddress>("[ACDManagerAddress]");
                }
                return this._ACDManagerAddress;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ACDManagerAddress> _ACDManagerAddress;
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddressGroup dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ACDManagerAddressGroup> ACDManagerAddressGroup
        {
            get
            {
                if ((this._ACDManagerAddressGroup == null))
                {
                    this._ACDManagerAddressGroup = base.CreateQuery<ACDManagerAddressGroup>("[ACDManagerAddressGroup]");
                }
                return this._ACDManagerAddressGroup;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ACDManagerAddressGroup> _ACDManagerAddressGroup;
        /// <summary>
        /// Il n'existe aucun commentaire pour Team dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Team> Team
        {
            get
            {
                if ((this._Team == null))
                {
                    this._Team = base.CreateQuery<Team>("[Team]");
                }
                return this._Team;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Team> _Team;
        /// <summary>
        /// Il n'existe aucun commentaire pour TeamMember dans le schéma.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TeamMember> TeamMember
        {
            get
            {
                if ((this._TeamMember == null))
                {
                    this._TeamMember = base.CreateQuery<TeamMember>("[TeamMember]");
                }
                return this._TeamMember;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TeamMember> _TeamMember;
        /// <summary>
        /// Il n'existe aucun commentaire pour Calls dans le schéma.
        /// </summary>
        public void AddToCalls(Calls calls)
        {
            base.AddObject("Calls", calls);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Codif dans le schéma.
        /// </summary>
        public void AddToCodif(Codif codif)
        {
            base.AddObject("Codif", codif);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddress dans le schéma.
        /// </summary>
        public void AddToACDManagerAddress(ACDManagerAddress aCDManagerAddress)
        {
            base.AddObject("ACDManagerAddress", aCDManagerAddress);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddressGroup dans le schéma.
        /// </summary>
        public void AddToACDManagerAddressGroup(ACDManagerAddressGroup aCDManagerAddressGroup)
        {
            base.AddObject("ACDManagerAddressGroup", aCDManagerAddressGroup);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Team dans le schéma.
        /// </summary>
        public void AddToTeam(Team team)
        {
            base.AddObject("Team", team);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour TeamMember dans le schéma.
        /// </summary>
        public void AddToTeamMember(TeamMember teamMember)
        {
            base.AddObject("TeamMember", teamMember);
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifModel.Calls dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// callid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CodifModel", Name="Calls")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Calls : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Calls.
        /// </summary>
        /// <param name="extension">Valeur initiale de extension.</param>
        /// <param name="calltype">Valeur initiale de calltype.</param>
        /// <param name="startdatetime">Valeur initiale de startdatetime.</param>
        /// <param name="callid">Valeur initiale de callid.</param>
        /// <param name="enddatetime">Valeur initiale de enddatetime.</param>
        public static Calls CreateCalls(string extension, string calltype, global::System.DateTime startdatetime, long callid, global::System.DateTime enddatetime)
        {
            Calls calls = new Calls();
            calls.extension = extension;
            calls.calltype = calltype;
            calls.startdatetime = startdatetime;
            calls.callid = callid;
            calls.enddatetime = enddatetime;
            return calls;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété extension dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string extension
        {
            get
            {
                return this._extension;
            }
            set
            {
                this.OnextensionChanging(value);
                this.ReportPropertyChanging("extension");
                this._extension = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("extension");
                this.OnextensionChanged();
            }
        }
        private string _extension;
        partial void OnextensionChanging(string value);
        partial void OnextensionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété callee dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string callee
        {
            get
            {
                return this._callee;
            }
            set
            {
                this.OncalleeChanging(value);
                this.ReportPropertyChanging("callee");
                this._callee = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("callee");
                this.OncalleeChanged();
            }
        }
        private string _callee;
        partial void OncalleeChanging(string value);
        partial void OncalleeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété calltype dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string calltype
        {
            get
            {
                return this._calltype;
            }
            set
            {
                this.OncalltypeChanging(value);
                this.ReportPropertyChanging("calltype");
                this._calltype = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("calltype");
                this.OncalltypeChanged();
            }
        }
        private string _calltype;
        partial void OncalltypeChanging(string value);
        partial void OncalltypeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété startdatetime dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime startdatetime
        {
            get
            {
                return this._startdatetime;
            }
            set
            {
                this.OnstartdatetimeChanging(value);
                this.ReportPropertyChanging("startdatetime");
                this._startdatetime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("startdatetime");
                this.OnstartdatetimeChanged();
            }
        }
        private global::System.DateTime _startdatetime;
        partial void OnstartdatetimeChanging(global::System.DateTime value);
        partial void OnstartdatetimeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété id dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private string _id;
        partial void OnidChanging(string value);
        partial void OnidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété caller dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string caller
        {
            get
            {
                return this._caller;
            }
            set
            {
                this.OncallerChanging(value);
                this.ReportPropertyChanging("caller");
                this._caller = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("caller");
                this.OncallerChanged();
            }
        }
        private string _caller;
        partial void OncallerChanging(string value);
        partial void OncallerChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété callid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long callid
        {
            get
            {
                return this._callid;
            }
            set
            {
                this.OncallidChanging(value);
                this.ReportPropertyChanging("callid");
                this._callid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("callid");
                this.OncallidChanged();
            }
        }
        private long _callid;
        partial void OncallidChanging(long value);
        partial void OncallidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété enddatetime dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime enddatetime
        {
            get
            {
                return this._enddatetime;
            }
            set
            {
                this.OnenddatetimeChanging(value);
                this.ReportPropertyChanging("enddatetime");
                this._enddatetime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("enddatetime");
                this.OnenddatetimeChanged();
            }
        }
        private global::System.DateTime _enddatetime;
        partial void OnenddatetimeChanging(global::System.DateTime value);
        partial void OnenddatetimeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Codif dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "FK_Calls_Calls", "Codif")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Codif Codif
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Codif>("CodifModel.FK_Calls_Calls", "Codif").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Codif>("CodifModel.FK_Calls_Calls", "Codif").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Codif dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Codif> CodifReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Codif>("CodifModel.FK_Calls_Calls", "Codif");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Codif>("CodifModel.FK_Calls_Calls", "Codif", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifModel.Codif dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// codifid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CodifModel", Name="Codif")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Codif : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Codif.
        /// </summary>
        /// <param name="codif1">Valeur initiale de codif1.</param>
        /// <param name="active">Valeur initiale de active.</param>
        /// <param name="codifid">Valeur initiale de codifid.</param>
        public static Codif CreateCodif(string codif1, bool active, int codifid)
        {
            Codif codif = new Codif();
            codif.codif1 = codif1;
            codif.active = active;
            codif.codifid = codifid;
            return codif;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codif1 dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string codif1
        {
            get
            {
                return this._codif1;
            }
            set
            {
                this.Oncodif1Changing(value);
                this.ReportPropertyChanging("codif1");
                this._codif1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("codif1");
                this.Oncodif1Changed();
            }
        }
        private string _codif1;
        partial void Oncodif1Changing(string value);
        partial void Oncodif1Changed();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété active dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this.ReportPropertyChanging("active");
                this._active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("active");
                this.OnactiveChanged();
            }
        }
        private bool _active;
        partial void OnactiveChanging(bool value);
        partial void OnactiveChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété codifid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int codifid
        {
            get
            {
                return this._codifid;
            }
            set
            {
                this.OncodifidChanging(value);
                this.ReportPropertyChanging("codifid");
                this._codifid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("codifid");
                this.OncodifidChanged();
            }
        }
        private int _codifid;
        partial void OncodifidChanging(int value);
        partial void OncodifidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Calls dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "FK_Calls_Calls", "Calls")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Calls> Calls
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Calls>("CodifModel.FK_Calls_Calls", "Calls");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Calls>("CodifModel.FK_Calls_Calls", "Calls", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifModel.ACDManagerAddress dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// acdmanageraddressid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CodifModel", Name="ACDManagerAddress")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ACDManagerAddress : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet ACDManagerAddress.
        /// </summary>
        /// <param name="acdmanageraddressid">Valeur initiale de acdmanageraddressid.</param>
        /// <param name="pattern">Valeur initiale de pattern.</param>
        public static ACDManagerAddress CreateACDManagerAddress(global::System.Guid acdmanageraddressid, string pattern)
        {
            ACDManagerAddress aCDManagerAddress = new ACDManagerAddress();
            aCDManagerAddress.acdmanageraddressid = acdmanageraddressid;
            aCDManagerAddress.pattern = pattern;
            return aCDManagerAddress;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété acdmanageraddressid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid acdmanageraddressid
        {
            get
            {
                return this._acdmanageraddressid;
            }
            set
            {
                this.OnacdmanageraddressidChanging(value);
                this.ReportPropertyChanging("acdmanageraddressid");
                this._acdmanageraddressid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("acdmanageraddressid");
                this.OnacdmanageraddressidChanged();
            }
        }
        private global::System.Guid _acdmanageraddressid;
        partial void OnacdmanageraddressidChanging(global::System.Guid value);
        partial void OnacdmanageraddressidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété pattern dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string pattern
        {
            get
            {
                return this._pattern;
            }
            set
            {
                this.OnpatternChanging(value);
                this.ReportPropertyChanging("pattern");
                this._pattern = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("pattern");
                this.OnpatternChanged();
            }
        }
        private string _pattern;
        partial void OnpatternChanging(string value);
        partial void OnpatternChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddressGroup dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddressGroup")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ACDManagerAddressGroup ACDManagerAddressGroup
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddressGroup").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddressGroup").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddressGroup dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ACDManagerAddressGroup> ACDManagerAddressGroupReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddressGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddressGroup", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifModel.ACDManagerAddressGroup dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// acdmanageraddressgroupid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CodifModel", Name="ACDManagerAddressGroup")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ACDManagerAddressGroup : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet ACDManagerAddressGroup.
        /// </summary>
        /// <param name="acdmanageraddressgroupid">Valeur initiale de acdmanageraddressgroupid.</param>
        /// <param name="acdmanageraddressgroupname">Valeur initiale de acdmanageraddressgroupname.</param>
        public static ACDManagerAddressGroup CreateACDManagerAddressGroup(global::System.Guid acdmanageraddressgroupid, string acdmanageraddressgroupname)
        {
            ACDManagerAddressGroup aCDManagerAddressGroup = new ACDManagerAddressGroup();
            aCDManagerAddressGroup.acdmanageraddressgroupid = acdmanageraddressgroupid;
            aCDManagerAddressGroup.acdmanageraddressgroupname = acdmanageraddressgroupname;
            return aCDManagerAddressGroup;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété acdmanageraddressgroupid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid acdmanageraddressgroupid
        {
            get
            {
                return this._acdmanageraddressgroupid;
            }
            set
            {
                this.OnacdmanageraddressgroupidChanging(value);
                this.ReportPropertyChanging("acdmanageraddressgroupid");
                this._acdmanageraddressgroupid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("acdmanageraddressgroupid");
                this.OnacdmanageraddressgroupidChanged();
            }
        }
        private global::System.Guid _acdmanageraddressgroupid;
        partial void OnacdmanageraddressgroupidChanging(global::System.Guid value);
        partial void OnacdmanageraddressgroupidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété acdmanageraddressgroupname dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string acdmanageraddressgroupname
        {
            get
            {
                return this._acdmanageraddressgroupname;
            }
            set
            {
                this.OnacdmanageraddressgroupnameChanging(value);
                this.ReportPropertyChanging("acdmanageraddressgroupname");
                this._acdmanageraddressgroupname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("acdmanageraddressgroupname");
                this.OnacdmanageraddressgroupnameChanged();
            }
        }
        private string _acdmanageraddressgroupname;
        partial void OnacdmanageraddressgroupnameChanging(string value);
        partial void OnacdmanageraddressgroupnameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddress dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddress")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ACDManagerAddress> ACDManagerAddress
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ACDManagerAddress>("CodifModel.FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddress");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ACDManagerAddress>("CodifModel.FK_ACDManagerAddress_ACDManagerAddressGroup", "ACDManagerAddress", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Team dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "FK_Team_ACDManagerAddressGroup", "Team")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Team> Team
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Team>("CodifModel.FK_Team_ACDManagerAddressGroup", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Team>("CodifModel.FK_Team_ACDManagerAddressGroup", "Team", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifModel.Team dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// teamid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CodifModel", Name="Team")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Team : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet Team.
        /// </summary>
        /// <param name="teamid">Valeur initiale de teamid.</param>
        /// <param name="teampattern">Valeur initiale de teampattern.</param>
        /// <param name="teamname">Valeur initiale de teamname.</param>
        /// <param name="teamdefaultdestination">Valeur initiale de teamdefaultdestination.</param>
        public static Team CreateTeam(global::System.Guid teamid, string teampattern, string teamname, string teamdefaultdestination)
        {
            Team team = new Team();
            team.teamid = teamid;
            team.teampattern = teampattern;
            team.teamname = teamname;
            team.teamdefaultdestination = teamdefaultdestination;
            return team;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teamid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid teamid
        {
            get
            {
                return this._teamid;
            }
            set
            {
                this.OnteamidChanging(value);
                this.ReportPropertyChanging("teamid");
                this._teamid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teamid");
                this.OnteamidChanged();
            }
        }
        private global::System.Guid _teamid;
        partial void OnteamidChanging(global::System.Guid value);
        partial void OnteamidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teampattern dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string teampattern
        {
            get
            {
                return this._teampattern;
            }
            set
            {
                this.OnteampatternChanging(value);
                this.ReportPropertyChanging("teampattern");
                this._teampattern = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("teampattern");
                this.OnteampatternChanged();
            }
        }
        private string _teampattern;
        partial void OnteampatternChanging(string value);
        partial void OnteampatternChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teamname dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string teamname
        {
            get
            {
                return this._teamname;
            }
            set
            {
                this.OnteamnameChanging(value);
                this.ReportPropertyChanging("teamname");
                this._teamname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("teamname");
                this.OnteamnameChanged();
            }
        }
        private string _teamname;
        partial void OnteamnameChanging(string value);
        partial void OnteamnameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teamdefaultdestination dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string teamdefaultdestination
        {
            get
            {
                return this._teamdefaultdestination;
            }
            set
            {
                this.OnteamdefaultdestinationChanging(value);
                this.ReportPropertyChanging("teamdefaultdestination");
                this._teamdefaultdestination = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("teamdefaultdestination");
                this.OnteamdefaultdestinationChanged();
            }
        }
        private string _teamdefaultdestination;
        partial void OnteamdefaultdestinationChanging(string value);
        partial void OnteamdefaultdestinationChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddressGroup dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "FK_Team_ACDManagerAddressGroup", "ACDManagerAddressGroup")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ACDManagerAddressGroup ACDManagerAddressGroup
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_Team_ACDManagerAddressGroup", "ACDManagerAddressGroup").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_Team_ACDManagerAddressGroup", "ACDManagerAddressGroup").Value = value;
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour ACDManagerAddressGroup dans le schéma.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ACDManagerAddressGroup> ACDManagerAddressGroupReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_Team_ACDManagerAddressGroup", "ACDManagerAddressGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ACDManagerAddressGroup>("CodifModel.FK_Team_ACDManagerAddressGroup", "ACDManagerAddressGroup", value);
                }
            }
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour TeamMember dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "TeamMemberTeam", "TeamMember")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TeamMember> TeamMember
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TeamMember>("CodifModel.TeamMemberTeam", "TeamMember");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TeamMember>("CodifModel.TeamMemberTeam", "TeamMember", value);
                }
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour CodifModel.TeamMember dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// teammemberid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CodifModel", Name="TeamMember")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TeamMember : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Créez un nouvel objet TeamMember.
        /// </summary>
        /// <param name="teammemberid">Valeur initiale de teammemberid.</param>
        /// <param name="teammembername">Valeur initiale de teammembername.</param>
        /// <param name="teammemberextension">Valeur initiale de teammemberextension.</param>
        /// <param name="issupervisor">Valeur initiale de issupervisor.</param>
        public static TeamMember CreateTeamMember(global::System.Guid teammemberid, string teammembername, string teammemberextension, bool issupervisor)
        {
            TeamMember teamMember = new TeamMember();
            teamMember.teammemberid = teammemberid;
            teamMember.teammembername = teammembername;
            teamMember.teammemberextension = teammemberextension;
            teamMember.issupervisor = issupervisor;
            return teamMember;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teammemberid dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid teammemberid
        {
            get
            {
                return this._teammemberid;
            }
            set
            {
                this.OnteammemberidChanging(value);
                this.ReportPropertyChanging("teammemberid");
                this._teammemberid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("teammemberid");
                this.OnteammemberidChanged();
            }
        }
        private global::System.Guid _teammemberid;
        partial void OnteammemberidChanging(global::System.Guid value);
        partial void OnteammemberidChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teammembername dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string teammembername
        {
            get
            {
                return this._teammembername;
            }
            set
            {
                this.OnteammembernameChanging(value);
                this.ReportPropertyChanging("teammembername");
                this._teammembername = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("teammembername");
                this.OnteammembernameChanged();
            }
        }
        private string _teammembername;
        partial void OnteammembernameChanging(string value);
        partial void OnteammembernameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété teammemberextension dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string teammemberextension
        {
            get
            {
                return this._teammemberextension;
            }
            set
            {
                this.OnteammemberextensionChanging(value);
                this.ReportPropertyChanging("teammemberextension");
                this._teammemberextension = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("teammemberextension");
                this.OnteammemberextensionChanged();
            }
        }
        private string _teammemberextension;
        partial void OnteammemberextensionChanging(string value);
        partial void OnteammemberextensionChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété issupervisor dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool issupervisor
        {
            get
            {
                return this._issupervisor;
            }
            set
            {
                this.OnissupervisorChanging(value);
                this.ReportPropertyChanging("issupervisor");
                this._issupervisor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("issupervisor");
                this.OnissupervisorChanged();
            }
        }
        private bool _issupervisor;
        partial void OnissupervisorChanging(bool value);
        partial void OnissupervisorChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété islogged dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> islogged
        {
            get
            {
                return this._islogged;
            }
            set
            {
                this.OnisloggedChanging(value);
                this.ReportPropertyChanging("islogged");
                this._islogged = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("islogged");
                this.OnisloggedChanged();
            }
        }
        private global::System.Nullable<bool> _islogged;
        partial void OnisloggedChanging(global::System.Nullable<bool> value);
        partial void OnisloggedChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Team dans le schéma.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CodifModel", "TeamMemberTeam", "Team")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Team> Team
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Team>("CodifModel.TeamMemberTeam", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Team>("CodifModel.TeamMemberTeam", "Team", value);
                }
            }
        }
    }
}
