//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4952
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Wybecom.TalkPortal.CTI.Proxy.CLS {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CallLogsServerSoap", Namespace="http://wybecom.org/talkportal/cti/calllogsserver")]
    public partial class CallLogsServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMissedCallsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlacedCallsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedCallsOperationCompleted;
        
        /// <remarks/>
        public CallLogsServer() {
            string urlSetting = System.Web.Configuration.WebConfigurationManager.AppSettings["CallLogsServer"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/CTIWebServices/CallLogsServer.asmx";
            }
        }
        
        /// <remarks/>
        public event GetMissedCallsCompletedEventHandler GetMissedCallsCompleted;
        
        /// <remarks/>
        public event GetPlacedCallsCompletedEventHandler GetPlacedCallsCompleted;
        
        /// <remarks/>
        public event GetReceivedCallsCompletedEventHandler GetReceivedCallsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wybecom.org/talkportal/cti/calllogsserver/GetMissedCalls", RequestNamespace="http://wybecom.org/talkportal/cti/calllogsserver", ResponseNamespace="http://wybecom.org/talkportal/cti/calllogsserver", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Call[] GetMissedCalls(string dn, string sort) {
            object[] results = this.Invoke("GetMissedCalls", new object[] {
                        dn,
                        sort});
            return ((Call[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMissedCalls(string dn, string sort, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMissedCalls", new object[] {
                        dn,
                        sort}, callback, asyncState);
        }
        
        /// <remarks/>
        public Call[] EndGetMissedCalls(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Call[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMissedCallsAsync(string dn, string sort) {
            this.GetMissedCallsAsync(dn, sort, null);
        }
        
        /// <remarks/>
        public void GetMissedCallsAsync(string dn, string sort, object userState) {
            if ((this.GetMissedCallsOperationCompleted == null)) {
                this.GetMissedCallsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMissedCallsOperationCompleted);
            }
            this.InvokeAsync("GetMissedCalls", new object[] {
                        dn,
                        sort}, this.GetMissedCallsOperationCompleted, userState);
        }
        
        private void OnGetMissedCallsOperationCompleted(object arg) {
            if ((this.GetMissedCallsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMissedCallsCompleted(this, new GetMissedCallsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wybecom.org/talkportal/cti/calllogsserver/GetPlacedCalls", RequestNamespace="http://wybecom.org/talkportal/cti/calllogsserver", ResponseNamespace="http://wybecom.org/talkportal/cti/calllogsserver", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Call[] GetPlacedCalls(string dn, string sort) {
            object[] results = this.Invoke("GetPlacedCalls", new object[] {
                        dn,
                        sort});
            return ((Call[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPlacedCalls(string dn, string sort, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPlacedCalls", new object[] {
                        dn,
                        sort}, callback, asyncState);
        }
        
        /// <remarks/>
        public Call[] EndGetPlacedCalls(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Call[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPlacedCallsAsync(string dn, string sort) {
            this.GetPlacedCallsAsync(dn, sort, null);
        }
        
        /// <remarks/>
        public void GetPlacedCallsAsync(string dn, string sort, object userState) {
            if ((this.GetPlacedCallsOperationCompleted == null)) {
                this.GetPlacedCallsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlacedCallsOperationCompleted);
            }
            this.InvokeAsync("GetPlacedCalls", new object[] {
                        dn,
                        sort}, this.GetPlacedCallsOperationCompleted, userState);
        }
        
        private void OnGetPlacedCallsOperationCompleted(object arg) {
            if ((this.GetPlacedCallsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlacedCallsCompleted(this, new GetPlacedCallsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wybecom.org/talkportal/cti/calllogsserver/GetReceivedCalls", RequestNamespace="http://wybecom.org/talkportal/cti/calllogsserver", ResponseNamespace="http://wybecom.org/talkportal/cti/calllogsserver", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Call[] GetReceivedCalls(string dn, string sort) {
            object[] results = this.Invoke("GetReceivedCalls", new object[] {
                        dn,
                        sort});
            return ((Call[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReceivedCalls(string dn, string sort, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReceivedCalls", new object[] {
                        dn,
                        sort}, callback, asyncState);
        }
        
        /// <remarks/>
        public Call[] EndGetReceivedCalls(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Call[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedCallsAsync(string dn, string sort) {
            this.GetReceivedCallsAsync(dn, sort, null);
        }
        
        /// <remarks/>
        public void GetReceivedCallsAsync(string dn, string sort, object userState) {
            if ((this.GetReceivedCallsOperationCompleted == null)) {
                this.GetReceivedCallsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedCallsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedCalls", new object[] {
                        dn,
                        sort}, this.GetReceivedCallsOperationCompleted, userState);
        }
        
        private void OnGetReceivedCallsOperationCompleted(object arg) {
            if ((this.GetReceivedCallsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedCallsCompleted(this, new GetReceivedCallsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/calllogsserver")]
    public partial class Call {
        
        private string callerField;
        
        private string calleeField;
        
        private string callIdField;
        
        private CallType typeField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        /// <remarks/>
        public string caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        public string callee {
            get {
                return this.calleeField;
            }
            set {
                this.calleeField = value;
            }
        }
        
        /// <remarks/>
        public string callId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
            }
        }
        
        /// <remarks/>
        public CallType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/calllogsserver")]
    public enum CallType {
        
        /// <remarks/>
        missed,
        
        /// <remarks/>
        placed,
        
        /// <remarks/>
        received,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetMissedCallsCompletedEventHandler(object sender, GetMissedCallsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMissedCallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMissedCallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Call[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Call[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetPlacedCallsCompletedEventHandler(object sender, GetPlacedCallsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlacedCallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlacedCallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Call[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Call[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetReceivedCallsCompletedEventHandler(object sender, GetReceivedCallsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedCallsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedCallsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Call[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Call[])(this.results[0]));
            }
        }
    }
}
