//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4952
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Wybecom.TalkPortal.CTI.Proxy {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StateServerSoap", Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStatus))]
    public partial class StateServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetLineControlOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAgentLineControlOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCallLogsOperationCompleted;
        
        /// <remarks/>
        public StateServer() {
            string urlSetting = System.Web.Configuration.WebConfigurationManager.AppSettings["StateServer"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost/CTIWebServices/StateServer.asmx";
            }
        }

        public StateServer(string uri)
        {
            if (uri != null && uri != "")
            {
                this.Url = uri;
            }
            else
            {
                this.Url = "http://localhost/CTIWebServices/StateServer.asmx";
            }
        }
        /// <remarks/>
        public event SetLineControlCompletedEventHandler SetLineControlCompleted;
        
        /// <remarks/>
        public event SetAgentLineControlCompletedEventHandler SetAgentLineControlCompleted;
        
        /// <remarks/>
        public event AddCallLogsCompletedEventHandler AddCallLogsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wybecom.org/talkportal/cti/stateserver/SetLineControl", RequestNamespace="http://wybecom.org/talkportal/cti/stateserver", ResponseNamespace="http://wybecom.org/talkportal/cti/stateserver", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetLineControl(LineControl lc) {
            object[] results = this.Invoke("SetLineControl", new object[] {
                        lc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetLineControl(LineControl lc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetLineControl", new object[] {
                        lc}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSetLineControl(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetLineControlAsync(LineControl lc) {
            this.SetLineControlAsync(lc, null);
        }
        
        /// <remarks/>
        public void SetLineControlAsync(LineControl lc, object userState) {
            if ((this.SetLineControlOperationCompleted == null)) {
                this.SetLineControlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLineControlOperationCompleted);
            }
            this.InvokeAsync("SetLineControl", new object[] {
                        lc}, this.SetLineControlOperationCompleted, userState);
        }
        
        private void OnSetLineControlOperationCompleted(object arg) {
            if ((this.SetLineControlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLineControlCompleted(this, new SetLineControlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wybecom.org/talkportal/cti/stateserver/SetAgentLineControl", RequestNamespace="http://wybecom.org/talkportal/cti/stateserver", ResponseNamespace="http://wybecom.org/talkportal/cti/stateserver", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetAgentLineControl(string extension, string agentid, AgentState state, CallCenterCall ccc) {
            object[] results = this.Invoke("SetAgentLineControl", new object[] {
                        extension,
                        agentid,
                        state,
                        ccc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAgentLineControl(string extension, string agentid, AgentState state, CallCenterCall ccc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetAgentLineControl", new object[] {
                        extension,
                        agentid,
                        state,
                        ccc}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSetAgentLineControl(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetAgentLineControlAsync(string extension, string agentid, AgentState state, CallCenterCall ccc) {
            this.SetAgentLineControlAsync(extension, agentid, state, ccc, null);
        }
        
        /// <remarks/>
        public void SetAgentLineControlAsync(string extension, string agentid, AgentState state, CallCenterCall ccc, object userState) {
            if ((this.SetAgentLineControlOperationCompleted == null)) {
                this.SetAgentLineControlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAgentLineControlOperationCompleted);
            }
            this.InvokeAsync("SetAgentLineControl", new object[] {
                        extension,
                        agentid,
                        state,
                        ccc}, this.SetAgentLineControlOperationCompleted, userState);
        }
        
        private void OnSetAgentLineControlOperationCompleted(object arg) {
            if ((this.SetAgentLineControlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAgentLineControlCompleted(this, new SetAgentLineControlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wybecom.org/talkportal/cti/stateserver/AddCallLogs", RequestNamespace="http://wybecom.org/talkportal/cti/stateserver", ResponseNamespace="http://wybecom.org/talkportal/cti/stateserver", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddCallLogs(string dn, Call call) {
            object[] results = this.Invoke("AddCallLogs", new object[] {
                        dn,
                        call});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddCallLogs(string dn, Call call, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddCallLogs", new object[] {
                        dn,
                        call}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAddCallLogs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddCallLogsAsync(string dn, Call call) {
            this.AddCallLogsAsync(dn, call, null);
        }
        
        /// <remarks/>
        public void AddCallLogsAsync(string dn, Call call, object userState) {
            if ((this.AddCallLogsOperationCompleted == null)) {
                this.AddCallLogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCallLogsOperationCompleted);
            }
            this.InvokeAsync("AddCallLogs", new object[] {
                        dn,
                        call}, this.AddCallLogsOperationCompleted, userState);
        }
        
        private void OnAddCallLogsOperationCompleted(object arg) {
            if ((this.AddCallLogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCallLogsCompleted(this, new AddCallLogsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public partial class LineControl : LineStatus {
        
        private LineControlConnection[] lineControlConnectionField;
        
        /// <remarks/>
        public LineControlConnection[] lineControlConnection {
            get {
                return this.lineControlConnectionField;
            }
            set {
                this.lineControlConnectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public partial class LineControlConnection {
        
        private TerminalState terminalStateField;
        
        private ConnectionState stateField;
        
        private ConnectionState remoteStateField;
        
        private string contactField;
        
        private string callidField;
        
        /// <remarks/>
        public TerminalState terminalState {
            get {
                return this.terminalStateField;
            }
            set {
                this.terminalStateField = value;
            }
        }
        
        /// <remarks/>
        public ConnectionState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public ConnectionState remoteState {
            get {
                return this.remoteStateField;
            }
            set {
                this.remoteStateField = value;
            }
        }
        
        /// <remarks/>
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string callid {
            get {
                return this.callidField;
            }
            set {
                this.callidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public enum TerminalState {
        
        /// <remarks/>
        idle,
        
        /// <remarks/>
        ringing,
        
        /// <remarks/>
        talking,
        
        /// <remarks/>
        held,
        
        /// <remarks/>
        bridged,
        
        /// <remarks/>
        inuse,
        
        /// <remarks/>
        dropped,
        
        /// <remarks/>
        unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public enum ConnectionState {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        idle,
        
        /// <remarks/>
        failed,
        
        /// <remarks/>
        disconnected,
        
        /// <remarks/>
        established,
        
        /// <remarks/>
        alerting,
        
        /// <remarks/>
        offered,
        
        /// <remarks/>
        queued,
        
        /// <remarks/>
        network_reached,
        
        /// <remarks/>
        network_alerting,
        
        /// <remarks/>
        initiated,
        
        /// <remarks/>
        dialing,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public partial class Call {
        
        private string callerField;
        
        private string calleeField;
        
        private string callIdField;
        
        private CallType typeField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        /// <remarks/>
        public string caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        public string callee {
            get {
                return this.calleeField;
            }
            set {
                this.calleeField = value;
            }
        }
        
        /// <remarks/>
        public string callId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
            }
        }
        
        /// <remarks/>
        public CallType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public enum CallType {
        
        /// <remarks/>
        missed,
        
        /// <remarks/>
        placed,
        
        /// <remarks/>
        received,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public partial class CallCenterCall {
        
        private string callerField;
        
        private string applicationDataField;
        
        private string lastredirectnumberField;
        
        private string[] callvariablesField;
        
        /// <remarks/>
        public string caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        public string applicationData {
            get {
                return this.applicationDataField;
            }
            set {
                this.applicationDataField = value;
            }
        }
        
        /// <remarks/>
        public string lastredirectnumber {
            get {
                return this.lastredirectnumberField;
            }
            set {
                this.lastredirectnumberField = value;
            }
        }
        
        /// <remarks/>
        public string[] callvariables {
            get {
                return this.callvariablesField;
            }
            set {
                this.callvariablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineControl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public partial class LineStatus {
        
        private string directoryNumberField;
        
        private string forwardField;
        
        private bool doNotDisturbField;
        
        private bool mwiOnField;
        
        private Status statusField;
        
        private string monitoredField;
        
        /// <remarks/>
        public string directoryNumber {
            get {
                return this.directoryNumberField;
            }
            set {
                this.directoryNumberField = value;
            }
        }
        
        /// <remarks/>
        public string forward {
            get {
                return this.forwardField;
            }
            set {
                this.forwardField = value;
            }
        }
        
        /// <remarks/>
        public bool doNotDisturb {
            get {
                return this.doNotDisturbField;
            }
            set {
                this.doNotDisturbField = value;
            }
        }
        
        /// <remarks/>
        public bool mwiOn {
            get {
                return this.mwiOnField;
            }
            set {
                this.mwiOnField = value;
            }
        }
        
        /// <remarks/>
        public Status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string monitored {
            get {
                return this.monitoredField;
            }
            set {
                this.monitoredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public enum Status {
        
        /// <remarks/>
        available,
        
        /// <remarks/>
        donotdisturb,
        
        /// <remarks/>
        forwarded,
        
        /// <remarks/>
        busy,
        
        /// <remarks/>
        hidden,
        
        /// <remarks/>
        dialing,
        
        /// <remarks/>
        ringing,
        
        /// <remarks/>
        inactive,
        
        /// <remarks/>
        unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wybecom.org/talkportal/cti/stateserver")]
    public enum AgentState {
        
        /// <remarks/>
        BUSY,
        
        /// <remarks/>
        LOG_IN,
        
        /// <remarks/>
        LOG_OUT,
        
        /// <remarks/>
        NOT_READY,
        
        /// <remarks/>
        READY,
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        WORK_NOT_READY,
        
        /// <remarks/>
        WORK_READY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SetLineControlCompletedEventHandler(object sender, SetLineControlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetLineControlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetLineControlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SetAgentLineControlCompletedEventHandler(object sender, SetAgentLineControlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAgentLineControlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAgentLineControlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void AddCallLogsCompletedEventHandler(object sender, AddCallLogsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCallLogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCallLogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
